# This workflow attempt to align taxonomic names
# from selected datasets 
# with selected taxonomic resources.
#
# For more information see: https://github.com/globalbioticinteractions/name-alignment-template

name: Name Alignment by Nomer

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  align:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' 
        java-version: '8'   
    - name: Download alignment script
      run: curl --silent -L "https://raw.githubusercontent.com/globalbioticinteractions/globinizer/master/align-names.sh" > align-names.sh
    - name: Align names
      run: bash align-names.sh "${GITHUB_REPOSITORY}"
    - name: Share alignment report
      uses: actions/upload-artifact@v3
      with:
        name: alignment-report
        path: |
          names-aligned.csv
          names-aligned.tsv
          names-aligned.txt
          names-aligned.html
          data/ 
